name: Build
on:
  pull_request:
  push:
    branches: [main]
    tags: ["v*"]
jobs:
  build:
    strategy:
      matrix:
        os: [windows-2025, macos-15, ubuntu-24.04]
        addrsize: ["64"]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: AlchemyViewer/action-autobuild@v5
        with:
          addrsize: ${{ matrix.addrsize }}
          apt-packages: ninja-build libdbus-1-dev libfreetype-dev libtbb-dev libwayland-dev wayland-protocols libxcursor-dev libxi-dev libxinerama-dev libxkbcommon-dev libxkbcommon-x11-dev libxrandr-dev libglvnd-dev libopengl-dev libgl-dev libegl-dev
          brew-packages: ninja
  release:
    needs: build
    runs-on: [ubuntu-latest]
    if: startsWith(github.ref, 'refs/tags/v')
    steps:
      - uses: AlchemyViewer/action-autobuild-release@v4
        with:
          public: true
